CREATE OR ALTER PROCEDURE SP_HealthDB_GetVitalSigns
    @RowId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM VitalSigns
    WHERE (ROWID = @RowId OR @RowId IS NULL)
    ORDER BY ROWID;
END;

