CREATE OR ALTER PROCEDURE SP_ShoppingDB_GetAPILogs
    @RowId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM APILogs
    WHERE (ROWID = @RowId OR @RowId IS NULL)
    ORDER BY ROWID;
END;

