CREATE OR ALTER PROCEDURE SP_ShoppingDB_GetStockAlerts
    @RowId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM StockAlerts
    WHERE (ROWID = @RowId OR @RowId IS NULL)
    ORDER BY ROWID;
END;

