CREATE OR ALTER PROCEDURE SP_ShoppingDB_GetErrorLogs
    @RowId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM ErrorLogs
    WHERE (ROWID = @RowId OR @RowId IS NULL)
    ORDER BY ROWID;
END;

