CREATE OR ALTER PROCEDURE SP_ShoppingDB_GetUserDevices
    @RowId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM UserDevices
    WHERE (ROWID = @RowId OR @RowId IS NULL)
    ORDER BY ROWID;
END;

