-- Ticketing Database - 25 Tables (Microsoft Dynamics GP style naming)
-- ROWID as PK, dex_row_id as unique identifier, full FK relationships

CREATE DATABASE TicketingDB;
GO
USE TicketingDB;
GO

-- ============================================================
-- TIER 0: No FK dependencies
-- ============================================================

-- TN00100 - TicketHeader (FK added below)
-- US00100 - CustomerMaster
-- SU00100 - AgentMaster
-- SU00200 - TeamMaster
-- CA00100 - CategoryMaster
-- ST00100 - StatusMaster
-- PR00100 - PriorityMaster
-- SL00100 - SLADefinition
-- KN00200 - ArticleCategory (KB)
-- RP00100 - ReportDefinition (no FKs)
-- NT00100 - NotificationTemplate
-- ES00100 - EscalationRule (FK added below)
-- AS00100 - AssignmentRule (FK added below)

-- US00100 - CustomerMaster
CREATE TABLE US00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    CUSTNMBR VARCHAR(20) UNIQUE NOT NULL,
    CUSTNAME NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    COMPANY NVARCHAR(100),
    ISACTIVE BIT DEFAULT 1,
    CREATEDDT DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO US00100 (dex_row_id, CUSTNMBR, CUSTNAME, EMAIL, PHONE, COMPANY) VALUES
('DEX001', 'CUST001', N'Budi Santoso', 'budi@email.com', '081234567890', N'PT Maju Jaya'),
('DEX002', 'CUST002', N'Siti Rahmawati', 'siti@email.com', '081234567891', N'CV Sejahtera'),
('DEX003', 'CUST003', N'Agus Prasetyo', 'agus@email.com', '081234567892', N'PT Makmur Abadi');
GO

-- SU00100 - AgentMaster
CREATE TABLE SU00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    AGENTID VARCHAR(20) UNIQUE NOT NULL,
    AGENTNAME NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    SKILLSET NVARCHAR(MAX),
    MAXASSIGNED INT DEFAULT 10,
    ISACTIVE BIT DEFAULT 1,
    HIREDT DATE
);
GO

INSERT INTO SU00100 (dex_row_id, AGENTID, AGENTNAME, EMAIL, PHONE, SKILLSET, MAXASSIGNED) VALUES
('DEX004', 'AGT001', N'Dewi Lestari', 'dewi@ticket.com', '081111111111', 'Technical Support, Billing', 15),
('DEX005', 'AGT002', N'Hendra Gunawan', 'hendra@ticket.com', '081111111112', 'Network, Hardware', 12),
('DEX006', 'AGT003', N'Rina Wijaya', 'rina@ticket.com', '081111111113', 'Software, Account Management', 10);
GO

-- SU00200 - TeamMaster
CREATE TABLE SU00200 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    TEAMID VARCHAR(20) UNIQUE NOT NULL,
    TEAMNAME NVARCHAR(100) NOT NULL,
    DESCRIPTION NVARCHAR(200),
    MANAGERID VARCHAR(20)
);
GO

INSERT INTO SU00200 (dex_row_id, TEAMID, TEAMNAME, DESCRIPTION) VALUES
('DEX007', 'TEAM01', N'Technical Support', N'Handles technical issues'),
('DEX008', 'TEAM02', N'Billing & Accounting', N'Payment and invoice issues'),
('DEX009', 'TEAM03', N'Customer Relations', N'Account and general inquiries');
GO

-- CA00100 - CategoryMaster
CREATE TABLE CA00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    CATID VARCHAR(20) UNIQUE NOT NULL,
    CATNAME NVARCHAR(100) NOT NULL,
    DESCRIPTION NVARCHAR(200)
);
GO

INSERT INTO CA00100 (dex_row_id, CATID, CATNAME, DESCRIPTION) VALUES
('DEX010', 'CAT01', N'Technical Issue', N'Software/hardware problems'),
('DEX011', 'CAT02', N'Billing Inquiry', N'Invoice, payment, refund questions'),
('DEX012', 'CAT03', N'Account Management', N'Password, profile, permissions');
GO

-- ST00100 - StatusMaster
CREATE TABLE ST00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    STATUSID VARCHAR(20) UNIQUE NOT NULL,
    STATUSNAME NVARCHAR(50) NOT NULL,
    SORTORDER INT DEFAULT 0,
    ISCLOSED BIT DEFAULT 0
);
GO

INSERT INTO ST00100 (dex_row_id, STATUSID, STATUSNAME, SORTORDER, ISCLOSED) VALUES
('DEX013', 'OPEN', 'Open', 1, 0),
('DEX014', 'INPROG', 'In Progress', 2, 0),
('DEX015', 'CLOSED', 'Closed', 3, 1);
GO

-- PR00100 - PriorityMaster
CREATE TABLE PR00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    PRIORITYID VARCHAR(20) UNIQUE NOT NULL,
    PRIORITYNAME NVARCHAR(50) NOT NULL,
    RESPONSETIMEHR INT,
    RESOLUTIONTIMEHR INT,
    COLOR VARCHAR(10)
);
GO

INSERT INTO PR00100 (dex_row_id, PRIORITYID, PRIORITYNAME, RESPONSETIMEHR, RESOLUTIONTIMEHR, COLOR) VALUES
('DEX016', 'LOW', 'Low', 24, 120, '#28a745'),
('DEX017', 'MED', 'Medium', 8, 48, '#ffc107'),
('DEX018', 'HIGH', 'High', 2, 8, '#dc3545');
GO

-- SL00100 - SLADefinition
CREATE TABLE SL00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    SLAID VARCHAR(20) UNIQUE NOT NULL,
    SLANAME NVARCHAR(100) NOT NULL,
    RESPONSETIMEHR INT NOT NULL,
    RESOLUTIONTIMEHR INT NOT NULL,
    ESCALATIONAFTERHR INT,
    ISACTIVE BIT DEFAULT 1
);
GO

INSERT INTO SL00100 (dex_row_id, SLAID, SLANAME, RESPONSETIMEHR, RESOLUTIONTIMEHR, ESCALATIONAFTERHR) VALUES
('DEX019', 'SLA01', 'Premium Support', 1, 4, 2),
('DEX020', 'SLA02', 'Standard Support', 4, 24, 8),
('DEX021', 'SLA03', 'Basic Support', 24, 72, 48);
GO

-- KN00200 - ArticleCategory (KB)
CREATE TABLE KN00200 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    ARTCATID VARCHAR(20) UNIQUE NOT NULL,
    ARTCATNAME NVARCHAR(100) NOT NULL
);
GO

INSERT INTO KN00200 (dex_row_id, ARTCATID, ARTCATNAME) VALUES
('DEX022', 'KBCAT01', 'Getting Started'),
('DEX023', 'KBCAT02', 'Troubleshooting'),
('DEX024', 'KBCAT03', 'FAQs');
GO

-- RP00100 - ReportDefinition
CREATE TABLE RP00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    RPTID VARCHAR(20) UNIQUE NOT NULL,
    RPTNAME NVARCHAR(100) NOT NULL,
    RPTTYPE VARCHAR(50),
    RPTXML NVARCHAR(MAX),
    ISACTIVE BIT DEFAULT 1
);
GO

INSERT INTO RP00100 (dex_row_id, RPTID, RPTNAME, RPTTYPE) VALUES
('DEX025', 'RPT01', 'Ticket Summary', 'Summary'),
('DEX026', 'RPT02', 'Agent Performance', 'Performance'),
('DEX027', 'RPT03', 'SLA Compliance', 'Compliance');
GO

-- NT00100 - NotificationTemplate
CREATE TABLE NT00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    NOTMPLID VARCHAR(20) UNIQUE NOT NULL,
    NOTMPLNAME NVARCHAR(100) NOT NULL,
    SUBJECT NVARCHAR(200),
    BODYHTML NVARCHAR(MAX),
    CHANNEL VARCHAR(20) CHECK (CHANNEL IN ('EMAIL', 'SMS', 'PUSH'))
);
GO

INSERT INTO NT00100 (dex_row_id, NOTMPLID, NOTMPLNAME, SUBJECT, CHANNEL) VALUES
('DEX028', 'TMPL01', 'New Ticket Acknowledgement', 'Your ticket #{{TICKET}} has been received', 'EMAIL'),
('DEX029', 'TMPL02', 'Status Update', 'Your ticket #{{TICKET}} status has changed', 'EMAIL'),
('DEX030', 'TMPL03', 'Escalation Notice', 'Ticket #{{TICKET}} has been escalated', 'EMAIL');
GO

-- ============================================================
-- TIER 1: Depends on Tier 0
-- ============================================================

-- SU00300 - AgentToTeam (FK: Agent, Team)
CREATE TABLE SU00300 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    AGENTROWID INT NOT NULL,
    TEAMROWID INT NOT NULL,
    ISLEAD BIT DEFAULT 0
);
GO

INSERT INTO SU00300 (dex_row_id, AGENTROWID, TEAMROWID, ISLEAD) VALUES
('DEX031', 1, 1, 1),
('DEX032', 2, 2, 1),
('DEX033', 3, 3, 0);
GO

ALTER TABLE SU00300 ADD CONSTRAINT FK_AGENTTEAM_AGENT FOREIGN KEY (AGENTROWID) REFERENCES SU00100(ROWID);
ALTER TABLE SU00300 ADD CONSTRAINT FK_AGENTTEAM_TEAM FOREIGN KEY (TEAMROWID) REFERENCES SU00200(ROWID);
GO

-- CA00200 - SubcategoryMaster (FK: Category)
CREATE TABLE CA00200 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    SUBCATID VARCHAR(20) UNIQUE NOT NULL,
    SUBCATNAME NVARCHAR(100) NOT NULL,
    CATROWID INT NOT NULL
);
GO

INSERT INTO CA00200 (dex_row_id, SUBCATID, SUBCATNAME, CATROWID) VALUES
('DEX034', 'SCAT01', 'Software Crash', 1),
('DEX035', 'SCAT02', 'Invoice Discrepancy', 2),
('DEX036', 'SCAT03', 'Password Reset', 3);
GO

ALTER TABLE CA00200 ADD CONSTRAINT FK_SUBCAT_CAT FOREIGN KEY (CATROWID) REFERENCES CA00100(ROWID);
GO

-- SL00200 - SLATarget (FK: SLA, Category)
CREATE TABLE SL00200 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    SLAROWID INT NOT NULL,
    CATROWID INT NOT NULL,
    RESPONSETIMEHR INT,
    RESOLUTIONTIMEHR INT
);
GO

INSERT INTO SL00200 (dex_row_id, SLAROWID, CATROWID, RESPONSETIMEHR, RESOLUTIONTIMEHR) VALUES
('DEX037', 1, 1, 1, 4),
('DEX038', 2, 2, 4, 24),
('DEX039', 3, 3, 24, 72);
GO

ALTER TABLE SL00200 ADD CONSTRAINT FK_SLATGT_SLA FOREIGN KEY (SLAROWID) REFERENCES SL00100(ROWID);
ALTER TABLE SL00200 ADD CONSTRAINT FK_SLATGT_CAT FOREIGN KEY (CATROWID) REFERENCES CA00100(ROWID);
GO

-- ES00100 - EscalationRule (FK: Priority, Team)
CREATE TABLE ES00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    RULEID VARCHAR(20) UNIQUE NOT NULL,
    RULENAME NVARCHAR(100) NOT NULL,
    PRIORITYROWID INT NOT NULL,
    TEAMROWID INT NOT NULL,
    TIMEOUTHR INT NOT NULL,
    ISACTIVE BIT DEFAULT 1
);
GO

INSERT INTO ES00100 (dex_row_id, RULEID, RULENAME, PRIORITYROWID, TEAMROWID, TIMEOUTHR) VALUES
('DEX040', 'ESCR01', 'High Priority Escalation', 3, 1, 2),
('DEX041', 'ESCR02', 'Medium Priority Escalation', 2, 2, 8),
('DEX042', 'ESCR03', 'SLA Breach Escalation', 2, 1, 4);
GO

ALTER TABLE ES00100 ADD CONSTRAINT FK_ESCRULE_PRIORITY FOREIGN KEY (PRIORITYROWID) REFERENCES PR00100(ROWID);
ALTER TABLE ES00100 ADD CONSTRAINT FK_ESCRULE_TEAM FOREIGN KEY (TEAMROWID) REFERENCES SU00200(ROWID);
GO

-- AS00100 - AssignmentRule (FK: Team, Category)
CREATE TABLE AS00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    RULEID VARCHAR(20) UNIQUE NOT NULL,
    RULENAME NVARCHAR(100) NOT NULL,
    TEAMROWID INT NOT NULL,
    CATROWID INT,
    METHOD VARCHAR(20) CHECK (METHOD IN ('ROUND_ROBIN', 'LEAST_BUSY', 'SKILL_BASED')),
    ISACTIVE BIT DEFAULT 1
);
GO

INSERT INTO AS00100 (dex_row_id, RULEID, RULENAME, TEAMROWID, CATROWID, METHOD) VALUES
('DEX043', 'ASSIGN01', 'Tech Issues to Tech Team', 1, 1, 'SKILL_BASED'),
('DEX044', 'ASSIGN02', 'Billing to Billing Team', 2, 2, 'ROUND_ROBIN'),
('DEX045', 'ASSIGN03', 'General to Customer Relations', 3, 3, 'LEAST_BUSY');
GO

ALTER TABLE AS00100 ADD CONSTRAINT FK_ASSIGNRULE_TEAM FOREIGN KEY (TEAMROWID) REFERENCES SU00200(ROWID);
ALTER TABLE AS00100 ADD CONSTRAINT FK_ASSIGNRULE_CAT FOREIGN KEY (CATROWID) REFERENCES CA00100(ROWID);
GO

-- KN00100 - ArticleMaster (KB) (FK: Agent, ArticleCategory)
CREATE TABLE KN00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    ARTICLEID VARCHAR(20) UNIQUE NOT NULL,
    TITLE NVARCHAR(200) NOT NULL,
    BODY NVARCHAR(MAX),
    ARTCATROWID INT NOT NULL,
    AUTHORROWID INT NOT NULL,
    VIEWCOUNT INT DEFAULT 0,
    ISPUBLISHED BIT DEFAULT 1,
    CREATEDDT DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO KN00100 (dex_row_id, ARTICLEID, TITLE, BODY, ARTCATROWID, AUTHORROWID) VALUES
('DEX046', 'KB001', 'How to Reset Password', N'Follow these steps to reset your password...', 1, 1),
('DEX047', 'KB002', 'Common Network Issues', N'Troubleshoot common network problems...', 2, 2),
('DEX048', 'KB003', 'Understanding Your Invoice', N'Learn how to read your monthly invoice...', 3, 3);
GO

ALTER TABLE KN00100 ADD CONSTRAINT FK_ARTICLE_AGENT FOREIGN KEY (AUTHORROWID) REFERENCES SU00100(ROWID);
ALTER TABLE KN00100 ADD CONSTRAINT FK_ARTICLE_ARTCAT FOREIGN KEY (ARTCATROWID) REFERENCES KN00200(ROWID);
GO

-- ============================================================
-- TIER 2: Depends on Tier 0-1
-- ============================================================

-- TN00100 - TicketHeader (Main ticket table)
CREATE TABLE TN00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    TICKETID VARCHAR(20) UNIQUE NOT NULL,
    CUSTOMERROWID INT NOT NULL,
    AGENTROWID INT,
    CATROWID INT NOT NULL,
    SUBCATROWID INT,
    STATUSROWID INT NOT NULL,
    PRIORITYROWID INT NOT NULL,
    SLAROWID INT,
    ASSIGNEDTEAMROWID INT,
    SUBJECT NVARCHAR(200) NOT NULL,
    DESCRIPTION NVARCHAR(MAX),
    SOURCE VARCHAR(20) CHECK (SOURCE IN ('EMAIL', 'PORTAL', 'PHONE', 'CHAT')),
    PRIORITYSCORE INT DEFAULT 0,
    RESPONDEDDT DATETIME,
    RESOLVEDDT DATETIME,
    CREATEDDT DATETIME DEFAULT GETDATE(),
    MODIFIEDDT DATETIME
);
GO

INSERT INTO TN00100 (dex_row_id, TICKETID, CUSTOMERROWID, CATROWID, STATUSROWID, PRIORITYROWID, SLAROWID, SUBJECT, SOURCE) VALUES
('DEX049', 'TKT-001', 1, 1, 1, 2, 2, N'Cannot connect to VPN', 'PORTAL'),
('DEX050', 'TKT-002', 2, 2, 2, 1, 2, N'Invoice #INV-2025-001 not received', 'EMAIL'),
('DEX051', 'TKT-003', 3, 3, 3, 3, 1, N'Account access revoked', 'PHONE');
GO

ALTER TABLE TN00100 ADD CONSTRAINT FK_TKT_CUSTOMER FOREIGN KEY (CUSTOMERROWID) REFERENCES US00100(ROWID);
ALTER TABLE TN00100 ADD CONSTRAINT FK_TKT_AGENT FOREIGN KEY (AGENTROWID) REFERENCES SU00100(ROWID);
ALTER TABLE TN00100 ADD CONSTRAINT FK_TKT_CAT FOREIGN KEY (CATROWID) REFERENCES CA00100(ROWID);
ALTER TABLE TN00100 ADD CONSTRAINT FK_TKT_SUBCAT FOREIGN KEY (SUBCATROWID) REFERENCES CA00200(ROWID);
ALTER TABLE TN00100 ADD CONSTRAINT FK_TKT_STATUS FOREIGN KEY (STATUSROWID) REFERENCES ST00100(ROWID);
ALTER TABLE TN00100 ADD CONSTRAINT FK_TKT_PRIORITY FOREIGN KEY (PRIORITYROWID) REFERENCES PR00100(ROWID);
ALTER TABLE TN00100 ADD CONSTRAINT FK_TKT_SLA FOREIGN KEY (SLAROWID) REFERENCES SL00100(ROWID);
ALTER TABLE TN00100 ADD CONSTRAINT FK_TKT_TEAM FOREIGN KEY (ASSIGNEDTEAMROWID) REFERENCES SU00200(ROWID);
GO

-- TN00200 - TicketDetail (messages / comments)
CREATE TABLE TN00200 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    DTLID VARCHAR(20) UNIQUE NOT NULL,
    TICKETROWID INT NOT NULL,
    AUTHORROWID INT NOT NULL,
    AUTHORTYPE VARCHAR(20) CHECK (AUTHORTYPE IN ('CUSTOMER', 'AGENT')),
    MESSAGETEXT NVARCHAR(MAX) NOT NULL,
    ISINTERNAL BIT DEFAULT 0,
    CREATEDDT DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO TN00200 (dex_row_id, DTLID, TICKETROWID, AUTHORROWID, AUTHORTYPE, MESSAGETEXT, ISINTERNAL) VALUES
('DEX052', 'DTL-001', 1, 1, 'CUSTOMER', N'I keep getting error 0x80072EFD when trying to connect.', 0),
('DEX053', 'DTL-002', 1, 1, 'AGENT', N'Please try clearing DNS cache and retry.', 0),
('DEX054', 'DTL-003', 1, 1, 'AGENT', N'Escalating to network team for further investigation.', 1);
GO

ALTER TABLE TN00200 ADD CONSTRAINT FK_DTL_TKT FOREIGN KEY (TICKETROWID) REFERENCES TN00100(ROWID);
ALTER TABLE TN00200 ADD CONSTRAINT FK_DTL_AUTHOR FOREIGN KEY (AUTHORROWID) REFERENCES SU00100(ROWID);
GO

-- TN00300 - TicketHistory (status audit)
CREATE TABLE TN00300 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    HISTID VARCHAR(20) UNIQUE NOT NULL,
    TICKETROWID INT NOT NULL,
    FROMSTATUSROWID INT,
    TOSTATUSROWID INT NOT NULL,
    CHANGEDBYTYPE VARCHAR(20) CHECK (CHANGEDBYTYPE IN ('CUSTOMER', 'AGENT', 'SYSTEM')),
    CHANGEDBYROWID INT,
    NOTES NVARCHAR(MAX),
    CHANGEDDT DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO TN00300 (dex_row_id, HISTID, TICKETROWID, TOSTATUSROWID, CHANGEDBYTYPE) VALUES
('DEX055', 'HIST-001', 1, 1, 'CUSTOMER'),
('DEX056', 'HIST-002', 1, 2, 'AGENT'),
('DEX057', 'HIST-003', 2, 1, 'CUSTOMER');
GO

ALTER TABLE TN00300 ADD CONSTRAINT FK_HIST_TKT FOREIGN KEY (TICKETROWID) REFERENCES TN00100(ROWID);
ALTER TABLE TN00300 ADD CONSTRAINT FK_HIST_FROMSTATUS FOREIGN KEY (FROMSTATUSROWID) REFERENCES ST00100(ROWID);
ALTER TABLE TN00300 ADD CONSTRAINT FK_HIST_TOSTATUS FOREIGN KEY (TOSTATUSROWID) REFERENCES ST00100(ROWID);
GO

-- AT00100 - AttachmentMaster (FK: Ticket)
CREATE TABLE AT00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    ATTACHID VARCHAR(20) UNIQUE NOT NULL,
    TICKETROWID INT NOT NULL,
    FILENAME VARCHAR(200) NOT NULL,
    FILEPATH VARCHAR(500) NOT NULL,
    FILESIZE INT,
    UPLOADEDBYROWID INT,
    UPLOADEDDT DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO AT00100 (dex_row_id, ATTACHID, TICKETROWID, FILENAME, FILEPATH) VALUES
('DEX058', 'ATT-001', 1, 'error_screenshot.png', '/uploads/tickets/001/screenshot.png'),
('DEX059', 'ATT-002', 2, 'invoice_request.pdf', '/uploads/tickets/002/invoice.pdf'),
('DEX060', 'ATT-003', 3, 'account_screenshot.png', '/uploads/tickets/003/account.png');
GO

ALTER TABLE AT00100 ADD CONSTRAINT FK_ATT_TKT FOREIGN KEY (TICKETROWID) REFERENCES TN00100(ROWID);
GO

-- ES00200 - EscalationHistory (FK: Ticket, EscalationRule)
CREATE TABLE ES00200 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    ESHISTID VARCHAR(20) UNIQUE NOT NULL,
    TICKETROWID INT NOT NULL,
    RULEROWID INT NOT NULL,
    FROMTEAMROWID INT,
    TOTEAMROWID INT NOT NULL,
    REASON NVARCHAR(MAX),
    ESCALATEDDT DATETIME DEFAULT GETDATE(),
    RESOLVEDDT DATETIME
);
GO

INSERT INTO ES00200 (dex_row_id, ESHISTID, TICKETROWID, RULEROWID, TOTEAMROWID, REASON) VALUES
('DEX061', 'ESH-001', 1, 1, 1, N'SLA breach imminent'),
('DEX062', 'ESH-002', 1, 3, 1, N'Issue requires senior engineer'),
('DEX063', 'ESH-003', 2, 2, 2, N'Billing department escalation');
GO

ALTER TABLE ES00200 ADD CONSTRAINT FK_ESH_TKT FOREIGN KEY (TICKETROWID) REFERENCES TN00100(ROWID);
ALTER TABLE ES00200 ADD CONSTRAINT FK_ESH_RULE FOREIGN KEY (RULEROWID) REFERENCES ES00100(ROWID);
ALTER TABLE ES00200 ADD CONSTRAINT FK_ESH_FROMTEAM FOREIGN KEY (FROMTEAMROWID) REFERENCES SU00200(ROWID);
ALTER TABLE ES00200 ADD CONSTRAINT FK_ESH_TOTEAM FOREIGN KEY (TOTEAMROWID) REFERENCES SU00200(ROWID);
GO

-- AS00200 - AssignmentHistory (FK: Ticket, Agent)
CREATE TABLE AS00200 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    ASHISTID VARCHAR(20) UNIQUE NOT NULL,
    TICKETROWID INT NOT NULL,
    FROMAGENTROWID INT,
    TOAGENTROWID INT NOT NULL,
    REASON NVARCHAR(MAX),
    ASSIGNEDDT DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO AS00200 (dex_row_id, ASHISTID, TICKETROWID, TOAGENTROWID, REASON) VALUES
('DEX064', 'ASH-001', 1, 1, N'Skill-based assignment'),
('DEX065', 'ASH-002', 2, 2, N'Round-robin assignment'),
('DEX066', 'ASH-003', 3, 3, N'Manager reassignment');
GO

ALTER TABLE AS00200 ADD CONSTRAINT FK_ASH_TKT FOREIGN KEY (TICKETROWID) REFERENCES TN00100(ROWID);
ALTER TABLE AS00200 ADD CONSTRAINT FK_ASH_FROMAGENT FOREIGN KEY (FROMAGENTROWID) REFERENCES SU00100(ROWID);
ALTER TABLE AS00200 ADD CONSTRAINT FK_ASH_TOAGENT FOREIGN KEY (TOAGENTROWID) REFERENCES SU00100(ROWID);
GO

-- NT00200 - NotificationLog (FK: Ticket, NotificationTemplate)
CREATE TABLE NT00200 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    NOTIFID VARCHAR(20) UNIQUE NOT NULL,
    TICKETROWID INT NOT NULL,
    TMPLROWID INT NOT NULL,
    RECIPIENT VARCHAR(100) NOT NULL,
    CHANNEL VARCHAR(20),
    STATUS VARCHAR(20) DEFAULT 'SENT',
    SENTDT DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO NT00200 (dex_row_id, NOTIFID, TICKETROWID, TMPLROWID, RECIPIENT, CHANNEL) VALUES
('DEX067', 'NOT-001', 1, 1, 'budi@email.com', 'EMAIL'),
('DEX068', 'NOT-002', 1, 2, 'budi@email.com', 'EMAIL'),
('DEX069', 'NOT-003', 2, 1, 'siti@email.com', 'EMAIL');
GO

ALTER TABLE NT00200 ADD CONSTRAINT FK_NOT_TKT FOREIGN KEY (TICKETROWID) REFERENCES TN00100(ROWID);
ALTER TABLE NT00200 ADD CONSTRAINT FK_NOT_TMPL FOREIGN KEY (TMPLROWID) REFERENCES NT00100(ROWID);
GO

-- LG00100 - AuditLog (system audit)
CREATE TABLE LG00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    AUDITID VARCHAR(20) UNIQUE NOT NULL,
    TICKETROWID INT,
    CUSTOMERROWID INT,
    AGENTROWID INT,
    ACTIONTYPE VARCHAR(50) NOT NULL,
    TABLENAME VARCHAR(50),
    RECORDROWID INT,
    OLDVALUE NVARCHAR(MAX),
    NEWVALUE NVARCHAR(MAX),
    IPADDRESS VARCHAR(50),
    AUDITDT DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO LG00100 (dex_row_id, AUDITID, TICKETROWID, CUSTOMERROWID, ACTIONTYPE, TABLENAME) VALUES
('DEX070', 'AUD-001', 1, 1, 'CREATE', 'TN00100'),
('DEX071', 'AUD-002', 1, NULL, 'STATUS_CHANGE', 'TN00100'),
('DEX072', 'AUD-003', 2, 2, 'CREATE', 'TN00100');
GO

ALTER TABLE LG00100 ADD CONSTRAINT FK_AUDIT_TKT FOREIGN KEY (TICKETROWID) REFERENCES TN00100(ROWID);
ALTER TABLE LG00100 ADD CONSTRAINT FK_AUDIT_CUST FOREIGN KEY (CUSTOMERROWID) REFERENCES US00100(ROWID);
ALTER TABLE LG00100 ADD CONSTRAINT FK_AUDIT_AGENT FOREIGN KEY (AGENTROWID) REFERENCES SU00100(ROWID);
GO

-- CF00100 - CustomFieldValue (dynamic fields per ticket)
CREATE TABLE CF00100 (
    ROWID INT IDENTITY(1,1) PRIMARY KEY,
    dex_row_id VARCHAR(50),
    CFVALUEID VARCHAR(20) UNIQUE NOT NULL,
    TICKETROWID INT NOT NULL,
    FIELDNAME VARCHAR(50) NOT NULL,
    FIELDTYPE VARCHAR(20) CHECK (FIELDTYPE IN ('TEXT', 'NUMBER', 'DATE', 'DROPDOWN')),
    FIELDVALUE NVARCHAR(MAX)
);
GO

INSERT INTO CF00100 (dex_row_id, CFVALUEID, TICKETROWID, FIELDNAME, FIELDTYPE, FIELDVALUE) VALUES
('DEX073', 'CFV-001', 1, 'Affected Users', 'NUMBER', '15'),
('DEX074', 'CFV-002', 2, 'Invoice Amount', 'NUMBER', '15000000'),
('DEX075', 'CFV-003', 3, 'Urgency Reason', 'TEXT', 'Cannot access critical system');
GO

ALTER TABLE CF00100 ADD CONSTRAINT FK_CFV_TKT FOREIGN KEY (TICKETROWID) REFERENCES TN00100(ROWID);
GO

PRINT 'TicketingDB created successfully with 25 tables (GP style) and 3 records each.';
GO
